#!/usr/bin/env ruby

$LOAD_PATH.unshift "#{ENV['HOME']}/WorkProjects/offline-ingest/lib/"

require 'offin/ingestor'
require 'datyl/config'
require 'offin/utils'
require 'offin/manifest'
require 'offin/mods'

Kernel.trap('INT')  { STDERR.puts "Interrupt"  ; exit }
Kernel.trap('HUP')  { STDERR.puts "Hangup"  ; exit }
Kernel.trap('PIPE') { STDERR.puts "Pipe Closed"  ; exit }

config = Datyl::Config.new("#{ENV['HOME']}/WorkProjects/offline-ingest/config.yml", 'default')

package_directory = ARGV[0]






manifest = Manifest.new(config, File.join(package_directory, 'manifest.xml'))

puts '', "Manifest Errors",   "---------------",   manifest.errors
puts '', "Manifest Warnings", "-----------------", manifest.warnings


puts '', ''

mods = Mods.new(config, File.join(package_directory, "#{File.basename(package_directory)}.xml"))

puts "mods well-formed?  #{mods.mods_wellformed?}"
puts "mods document? #{mods.mods_document?}"
puts "mods validates? #{mods.mods_validates?}"

puts '', "MODS Errors",   "-----------",    mods.errors
puts '', "MODS Warnings", "-------------",  mods.warnings
