#!/usr/bin/env ruby

Kernel.trap('INT')  { STDERR.puts "Interrupt"    ; exit -1 }
Kernel.trap('HUP')  { STDERR.puts "Hangup"       ; exit -2 }
Kernel.trap('PIPE') { STDERR.puts "Pipe Closed"  ; exit -3 }

$LOAD_PATH.unshift "#{ENV['HOME']}/WorkProjects/offline-ingest/lib/"

require 'offin/packages'

Utils.ingest_usage if ARGV.empty?

config  = Datyl::Config.new("#{ENV['HOME']}/WorkProjects/offline-ingest/config.yml", "default", "i7d")

# if config.http_proxy
#   ENV['HTTP_PROXY'] = config.http_proxy
#   ENV['http_proxy'] = config.http_proxy
# end

factory = PackageFactory.new(config)

$stdout.sync = true

ARGV.each do |directory|

  begin
    started = Time.now
    package = factory.new_package(directory)

    raise "Invalid package in #{directory}." unless package.valid?

    package.updater = DigitoolMetadataUpdater
    package.process
    puts sprintf("%5.2f %s::%s => %s (%s)", Time.now - started, package.class, package.name, package.collections.join(', '), package.label)
  rescue => e
    STDERR.puts "Caught #{e.class} - #{e.message}"
  ensure
    STDERR.puts 'Errors:', package.errors, '' if package.errors?
    STDERR.puts 'Warnings:', package.warnings, '' if package.warnings?
  end

end
