#!/usr/bin/env ruby

$LOAD_PATH.unshift  "/usr/local/islandora/offline-ingest/lib/"

require 'rubygems'
require 'socket'
require 'offin/config'
require 'offin/db'

DataBase.debug = true
DataBase.add_ftp_tables(Datyl::Config.new("/usr/local/islandora/offline-ingest/config.yml", 'default', 'islandora7d'))
