#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), "../lib"))

require 'rubygems'
require 'offin/packages'
require 'offin/db'
require 'offin/config'
require 'watch-queue/utils'
require 'watch-queue/watch-directory'


CONFIG_FILE = "/usr/local/islandora/offline-ingest/config.yml"
REREAD = 60
PAUSE  = 5    # PAUSE should divide REREAD evenly


DataBase.setup(Datyl::Config.new(CONFIG_FILE, 'default'))

counter = 0

# TODO: catch format errors in the config file

while true
  wds = watch_these_directories(CONFIG_FILE)  if (counter % REREAD == 0)   # we'll re-read config file every REREAD seconds or so to catch changes
  wds.each { |wd|  wd.enqueue_incoming_packages }
  sleep(PAUSE)
  counter += PAUSE
end
