#!/usr/bin/env ruby
$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '../lib')

require 'rubygems'
require 'mono_logger'
require 'resque'
require 'watch-queue/ingest-job'
require 'watch-queue/watch-directory'

SLEEP_INTERVAL = 1

logger  = MonoLogger.new('/tmp/resque.log')   # TODO: syslog as well?  Needs write/close
logger.level = MonoLogger::INFO               # TODO: set this from config file

logger.debug("#{$0}: watching '/tmp/fischer'")


wd = WatchDirectory.new('/tmp/fischer')

while true
  dirs = wd.ready_directories()

  if dirs.empty?
    logger.debug("#{$0}: no recent dirs")
    sleep SLEEP_INTERVAL
  else
    logger.info("#{$0}: processing the following directories: #{dirs.join(', ')}")
  end

  dirs.each do |src|
    dest = File.join(wd.create_new_processing_directory(), File.basename(src))
    logger.debug("#{$0}: moving #{src} to #{dest}")
    FileUtils.mv(src, dest)

    Resque.enqueue(IngestJob, 'fsu')
    logger.info "#{$0}: enqueued #{dest}"
  end
end
