#!/usr/bin/env ruby

$LOAD_PATH.unshift case Socket.gethostname
                   when /alpo/i;                                "/home/fischer/WorkProjects/offline-ingest/lib/"
                   when /romeo-foxtrot|flvc-rfischer.local/i;   "/Users/fischer/WorkProjects/offline-ingest/lib/"
                   when /islandora[dtp]/i;                      "/usr/local/islandora/offline-ingest/lib/"
                   else
                     STDERR.puts "#{$0} Doesn't know how to configure for this environment (#{Socket.gethostname.downcase}), quitting."
                     exit -1
                   end

require 'rubydora'
require 'offlin/ingest-support'


# Extend RI mixins to include itql queries:

module Rubydora
  module ResourceIndex
    def itql query
      if CSV.const_defined? :Reader
        FasterCSV.parse(self.risearch(query, :lang => 'itql', :format => 'TSV'), :headers => false)
      else
        CSV.parse(self.risearch(query, :lang => 'itql', :format => 'TSV'), :headers => false)
      end
    end
  end
end

def connect config
    repository = Rubydora.connect :url => config.url, :user => config.user, :password => config.password
    repository.ping
    return repository
end

config = get_config 'fsu7prod'
repository = connect config


query = <<-EOF
    select $child $parent $child_title from <#ri>
    where  $child <fedora-model:hasModel> <info:fedora/islandora:collectionCModel>
    and    $child <fedora-model:label> $child_title
    and    $child <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> $parent
    and    $child <fedora-model:hasModel> <info:fedora/islandora:collectionCModel>
EOF


puts repository.itql(query).inspect



# All collection child-collections:


#     select $child $parent $child_title from <#ri>
#     where  $child <fedora-model:hasModel> <info:fedora/islandora:collectionCModel>
#     and    $child <fedora-model:label> $child_title
#     and    $child <info:fedora/fedora-system:def/relations-external#isMemberOfCollection> $parent
#     and    $child <fedora-model:hasModel> <info:fedora/islandora:collectionCModel>
#
# TSV:

# child	parent	child_title
# info:fedora/islandora:sp_basic_image_collection	info:fedora/islandora:root	Basic Image Collection
# info:fedora/islandora:sp_pdf_collection	info:fedora/islandora:root	PDF Collection
# info:fedora/islandora:audio_collection	info:fedora/islandora:root	Audio Collection
# info:fedora/islandora:bookCollection	info:fedora/islandora:root	Book Collection
# info:fedora/islandora:sp_large_image_collection	info:fedora/islandora:root	Large Image Collection
# info:fedora/fsu:specialcol	info:fedora/fsu:root	Special Collections and Archives
# info:fedora/fsu:hpmain	info:fedora/fsu:root	Heritage Protocol and University Archives
# info:fedora/fsu:civilwarmain	info:fedora/fsu:specialcol	Civil War Era Collections
# info:fedora/fsu:sayrecircus	info:fedora/fsu:specialcol	Harrison Sayre Circus Collection
# info:fedora/fsu:diraccol	info:fedora/fsu:specialcol	Paul A.M. Dirac Collection
# info:fedora/fsu:fsulivesmain	info:fedora/fsu:hpmain	FSU Lives: Portal to the Past, Prologue to the Future
# info:fedora/fsu:fsy50	info:fedora/fsu:fsulivesmain	Yearbooks
# info:fedora/fsu:fsr50	info:fedora/fsu:fsulivesmain	President's Report
# info:fedora/fsu:fce06	info:fedora/fsu:fsulivesmain	Commencement
# info:fedora/fsu:colgradschpubsmain	info:fedora/fsu:fsulivesmain	College and Graduate School Publications
# info:fedora/fsu:acadlifemain	info:fedora/fsu:fsulivesmain	Academic Life
# info:fedora/fsu:stucamplifemain	info:fedora/fsu:fsulivesmain	Student and Campus Life
# info:fedora/fsu:artoncampusmain	info:fedora/fsu:fsulivesmain	Art on Campus
# info:fedora/fsu:alp55	info:fedora/fsu:colgradschpubsmain	School of Library Training and Service
# info:fedora/fsu:apa55	info:fedora/fsu:colgradschpubsmain	School of Public Administration
# info:fedora/fsu:asb50	info:fedora/fsu:colgradschpubsmain	School of Business
# info:fedora/fsu:asj50	info:fedora/fsu:colgradschpubsmain	School of Journalism
# info:fedora/fsu:asw55	info:fedora/fsu:colgradschpubsmain	School of Social Welfare
# info:fedora/fsu:ave52	info:fedora/fsu:colgradschpubsmain	School of Education
# info:fedora/fsu:avn50	info:fedora/fsu:colgradschpubsmain	School of Nursing
# info:fedora/fsu:afs50	info:fedora/fsu:colgradschpubsmain	College of Arts and Sciences
# info:fedora/fsu:fgb04	info:fedora/fsu:colgradschpubsmain	Graduate Bulletin
# info:fedora/fsu:fub05	info:fedora/fsu:colgradschpubsmain	Undergraduate Bulletin
# info:fedora/fsu:fhe55	info:fedora/fsu:colgradschpubsmain	School of Home Economics
# info:fedora/fsu:acw50	info:fedora/fsu:acadlifemain	Conferences and Workshops
# info:fedora/fsu:aes50	info:fedora/fsu:acadlifemain	Examination Schedules
# info:fedora/fsu:ave50	info:fedora/fsu:acadlifemain	Enrollment
# info:fedora/fsu:afl55	info:fedora/fsu:acadlifemain	Lecture Programs
# info:fedora/fsu:flc50	info:fedora/fsu:acadlifemain	Class Schedules
# info:fedora/fsu:avc50	info:fedora/fsu:stucamplifemain	Flying High Circus
# info:fedora/fsu:afg50	info:fedora/fsu:stucamplifemain	Gymkana
# info:fedora/fsu:avh50	info:fedora/fsu:stucamplifemain	Homecoming
# info:fedora/fsu:avm50	info:fedora/fsu:stucamplifemain	Marching Chiefs
# info:fedora/fsu:football50	info:fedora/fsu:stucamplifemain	Football
# info:fedora/fsu:fsp50	info:fedora/fsu:stucamplifemain	Pow Wow Student Handbooks
# info:fedora/fsu:fsi07	info:fedora/fsu:stucamplifemain	Investiture Ceremonies
# info:fedora/fsu:avp51	info:fedora/fsu:stucamplifemain	Panhellenic Rushing Rules
# info:fedora/fsu:aas50	info:fedora/fsu:artoncampusmain	Artist Series
# info:fedora/fsu:avf50	info:fedora/fsu:artoncampusmain	Art Gallery
# info:fedora/fsu:amp55	info:fedora/fsu:artoncampusmain	Musical Performances
# info:fedora/fsu:avd50	info:fedora/fsu:artoncampusmain	Theater and Dance Performances
# info:fedora/fsu:cwhb	info:fedora/fsu:civilwarmain	Captain Hugh Black Papers
# info:fedora/fsu:cwm	info:fedora/fsu:civilwarmain	Confederate Money
# info:fedora/fsu:spc12	info:fedora/fsu:sayrecircus	Photographs
# info:fedora/fsu:spc11	info:fedora/fsu:sayrecircus	Posters
