#!/usr/bin/env ruby

# TODO: expire the errors/ and warnings/ directories in here.

# This script starts a worker process for ingesting a package listed
# on a resque queue name :ingest.  Multiple workers are created by
# invoking this script multiple times.  Normally we'll have a
# process-monitor such as god manage that startup.  See /etc/god.conf.

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '../lib'))

require 'rubygems'
require 'offin/config'
require 'offin/exceptions'
require 'resque'
require 'watch-queue/watch-utils'

WORKER_SLEEP = 5
SYSTEM_ERROR_SLEEP = 60
UNHANDLED_ERROR_SLEEP = 600

# A process monitor will restart an instance of this script if we exit on error.

queues = ARGV

begin
  config = WatchUtils.setup_config()
  WatchUtils.setup_resque_logger()
  WatchUtils.setup_redis_connection(config)
  WatchUtils.start_ingest_worker(WORKER_SLEEP, queues)

rescue Redis::CannotConnectError, SystemError => e
  Resque.logger.error "System error: #{e.message}; sleeping for #{SYSTEM_ERROR_SLEEP} seconds."
  sleep SYSTEM_ERROR_SLEEP
  exit

rescue => e
  Resque.logger.error "Unexpected error: #{e.class}: #{e.message}; sleeping for #{UNHANDLED_ERROR_SLEEP/60} minutes.  Backtrace follows:"
  e.backtrace.each { |line| Resque.logger.error line }
  sleep UNHANDLED_ERROR_SLEEP
  exit
end
