#!/usr/bin/env ruby
$LOAD_PATH.unshift File.join(File.dirname(__FILE__), '../lib')

NUMBER_OF_WORKERS = 2

require 'rubygems'
require 'mono_logger'
require 'resque'
require 'watch-queue/ingest-job'

Resque.logger = MonoLogger.new('/tmp/resque.log')   # TODO: syslog as well?  Needs write/close
Resque.logger.level = MonoLogger::INFO

worker = Resque::Worker.new('ingest')

worker.term_timeout = 1.0
worker.term_child = 1
worker.work(NUMBER_OF_WORKERS)
