#!/usr/bin/env ruby

$LOAD_PATH.unshift "/usr/local/islandora/offline-ingest/lib/"

require 'offin/config'
require 'offin/manifest'

Kernel.trap('INT')  { STDERR.puts "Interrupt"  ; exit }
Kernel.trap('HUP')  { STDERR.puts "Hangup"  ; exit }
Kernel.trap('PIPE') { STDERR.puts "Pipe Closed"  ; exit }

config = Datyl::Config.new("/usr/local/islandora/offline-ingest/config.yml", 'default')

manifest = Manifest.new(config, ARGV[0])

puts "Valid? #{manifest.valid?}"

if manifest.errors?
  puts "Errors: ", manifest.errors
end

if manifest.warnings?
  puts "Warnings: ", manifest.warnings
end

puts manifest.embargo.inspect
